@startuml Architecture
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml


System(org, "Организация", "Заинтересована в собственной эффективности и репутации")
Person(initiator, "Инициатор", "Пишет предложение по усовершенствованию или жалобу(сначала непублично)")
Person(voter, "Голосующий", "Просматривает список предложенных усовершенствований и голосует")
System(platform, "Platform", "Система отбора лучших предложений и направления жалоб, ведения статистики по организациям, контроля выполнения")
System(community, "Сообщество", "Например, профсоюз машинисток трамваев, врачей, деятелей культуры, общество по защите потребителей. Продвигает инициативы в определённой отрасли")
Person(contractor, "Подрядчик", "Предлагает сови проекты в случае объявления Oрганизацией конкурса")
System_Ext(verification, "Система верификации", "Верификация")

Rel(org, platform, "Реагирует на предложения")
Rel(initiator, platform, "Создаёт предложение")
Rel(contractor, platform, "Создаёт конкурсное предложение")
Rel(voter, platform, "Голосует зa предложение")
Rel_L(platform, verification, "Запрос на верификацию личности")
Rel(community, platform, "Продвигает инициативы")

Lay_U(voter, org)
@enduml