@startuml High Level Architecture
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml


System_Boundary(org, "Организация"){
    Person(ceo, "Глава", "Руководит организацией")
    Person(staff1, "Представитель", "1 уровень")
    Person(staff2, "...", "...")
    Person(staffn, "Представитель", "n уровень")
}
Rel(ceo, staff1,"Контролирует")
Rel(staff1, staff2,"Контролирует")
Rel(staff2, staffn,"Контролирует")

System_Boundary(community, "Сообщество"){
    Person(main_volunteer, "Глава", "Руководит сообществом")
    Person(volunteer1, "Участник", "1 уровень")
    Person(volunteer2, "...", "...")
    Person(volunteern, "Участник", "n уровень")
}
Rel(main_volunteer, volunteer1,"Взаимодействует")
Rel(volunteer1, volunteer2,"Взаимодействует")
Rel(volunteer2, volunteern,"Взаимодействует")


Person(initiator, "Инициатор", "Пишет жалобу или предложение по усовершенствованию")
Person(voter, "Голосующий", "Просматривает список предложенных усовершенствований и голосует")
Person(contractor, "Подрядчик", "Участвует в конкурсах, открытых организациями")
System_Boundary(app, "Platform"){
    Container(community_app, "Приложение участника сообщества", "Участники сообщества взаимодействуют друг с другом при помощи этого приложения")
    Container(contractor_app, "Приложение подрядчика", "Просмотр открытых конкурсов и добавление своих предложений")
    Container(add, "Приложение Инициатора", "Добавление предложения")
    Container(vote, "Приложение Голосующего", "Показ релевантных предложений с возможностью голосования за них")
    Container(react, "Приложение представителя организации", "Представители организации взаимодействуют друг с другом при помощи этого приложения")
    Container(sys, "Система", "Обрабатывает данные")
    ContainerDb(db, "База данных предложений и жалоб", "Наверное, H2")
}

System_Ext(verify, "Система верификации", "Верифицирует личность")

Rel_L(staffn, react, "Реагирует на инициативы и жалобы")
Rel_D(volunteern, community_app, "Взаимодействие с сообществом")

Rel(initiator, add, "Создаёт предложение")
Rel(voter, vote, "Голосует зa предложение")
Rel(contractor, contractor_app, "Создаёт конкурсное предложение")

Rel_D(add, sys, "Добавляет инициативу")
Rel(vote, sys, "Голосует")
Rel(react, sys, "Реагирует на инициативы")
Rel(contractor_app, sys, "Добавление конкурсного предложения")
Rel(community_app, sys, "Взаимодействует")
Rel(sys, db, "Получает, изменяет и добавляет данные")
Rel_R(sys, verify, "Запрос на верификацию личности")
@enduml