@startuml High Level Architecture
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml


Person(org, "Организация", "Организация, к которой направляются предложения по усовершенствованию")
Person(initiator, "Инициатор", "Пишет жалобу или предложение по усовершенствованию")
Person(voter, "Голосующий", "Просматривает список предложенных усовершенствований и голосует")
System_Boundary(app, "In Ideas"){
    Container(add, "Приложение Инициатора", "Добавление предложения")
    Container(vote, "Приложение Голосующегор", "Показ существующих предложений с возможностью голосования за них")
    Container(react, "Приложение Организации", "Просмотр предложений, направленных к организации.")
    ContainerDb(db, "База данных идей, предложений и жалоб", "Наверное, H2")
}


Rel_D(org, react, "Реагирует на предложения")
Rel_D(add, db, "Хранит и получает данные")
Rel(vote, db, "Хранит и получает данные")
Rel(react, db, "Хранит и получает данные")
Rel(initiator, add, "Создаёт предложение")
Rel(voter, vote, "Голосует зa предложение")
@enduml